# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:categories/:year/:month/:day/:title 
relative_permalinks: true

# Setup
title:               'ljnchn'
tagline:             'I can do beter.'
description:         '何处是归途。'
url:                 http://ljnchn.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              ljnchn
  url:               https://twitter.com/ljnchn
  email:             uplees@gmail.com

