# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               '不选择开始，就不会有开始'
tagline:             'I can do beter.'
description:         '何处是归途。'
url:                 http://ljnchn.github.io
baseurl:             http://ljnchn.github.io
paginate:            5

# About/contact
author:
  name:              ljnchn
  url:               https://twitter.com/ljnchn
  email:             uplees@gmail.com

