# Dependencies
markdown:            kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:categories/:year/:month/:day/:title

# Setup
title:               'ljnchn'
tagline:             'I can do beter.'
description:         '何处是归途。'
url:                 https://ljnchn.github.io/
baseurl:             https://ljnchn.github.io/
paginate:            5

disqus:
  id: ljnchn

# About/contact
author:
  name:              ljnchn
  url:               https://twitter.com/ljnchn
  email:             uplees@gmail.com
